# Multi-stage Dockerfile for Render (Node + Vite build)
FROM node:20-alpine AS builder
WORKDIR /app

# Enable corepack and prepare pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy manifest and install deps (use pnpm by packageManager)
COPY package.json pnpm-lock.yaml* ./
COPY . .
RUN pnpm install --frozen-lockfile --reporter=silent

# Build client and server
RUN npm run build

# Final runtime image
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

# Copy built artifacts and production node_modules from builder
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000

# Use the built server entry generated by vite (production.mjs)
CMD ["node", "dist/server/production.mjs"]
